# Generated by Django 2.2.4 on 2019-08-06 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190806_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 6, 8, 51, 22, 149726, tzinfo=utc)),
        ),
    ]
