# Generated by Django 2.2.4 on 2019-08-06 06:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=datetime.datetime(2019, 8, 6, 6, 50, 22, 773167, tzinfo=utc))),
                ('is_published', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('published_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('discounted_price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=10)),
                ('image', models.FileField(blank=True, max_length=150, null=True, upload_to='deals')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 8, 6, 6, 50, 22, 773688, tzinfo=utc))),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
