# Generated by Django 2.2.4 on 2019-08-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190806_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='published_date',
            field=models.DateField(default=None, unique=True),
        ),
    ]
